"""
Pydantic models for the Root Agent agent API.

These models cover the full lifecycle of an agent run:
  AgentStatus  — enum of possible run states
  ToolCall     — a single tool invocation requested by the LLM
  ToolResult   — the outcome of executing a ToolCall
  AgentRun     — the top-level record for one analysis session
"""

from datetime import datetime, timezone
from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------


class AgentStatus(str, Enum):
    """Lifecycle states for an AgentRun."""

    PENDING = "pending"
    """Run has been created but the agent loop has not started yet."""

    RUNNING = "running"
    """The agent loop is actively iterating (calling Claude and tools)."""

    AWAITING_APPROVAL = "awaiting_approval"
    """The agent wants to apply a cluster fix but is waiting for human sign-off."""

    COMPLETED = "completed"
    """The agent finished successfully."""

    FAILED = "failed"
    """The agent encountered an unrecoverable error."""

    CANCELLED = "cancelled"
    """The run was manually cancelled before completion."""


# ---------------------------------------------------------------------------
# Tool call / result models
# ---------------------------------------------------------------------------


class ToolCall(BaseModel):
    """
    A single tool invocation emitted by the Claude model during an agent step.

    Mirrors the structure returned by the Anthropic API's tool_use content block.
    """

    tool_use_id: str = Field(
        description="Unique identifier for this tool call, generated by the Anthropic API."
    )
    name: str = Field(
        description="Name of the tool being called (e.g. 'get_pod_logs', 'apply_fix')."
    )
    input: dict[str, Any] = Field(
        description="Parsed input arguments the model passed to the tool."
    )
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp of when the tool call was emitted.",
    )

    model_config = ConfigDict(json_schema_extra={
            "example": {
                "tool_use_id": "toolu_01XzY",
                "name": "get_pod_logs",
                "input": {"pod_name": "api-server-7d9f", "namespace": "production", "tail_lines": 50},
                "timestamp": "2024-01-15T10:30:00Z",
            }
        })


class ToolResult(BaseModel):
    """
    The outcome of executing a ToolCall, sent back to Claude as a tool_result block.
    """

    tool_use_id: str = Field(
        description="Must match the tool_use_id of the corresponding ToolCall."
    )
    name: str = Field(description="Tool name, mirrored from the ToolCall for convenience.")
    output: str | dict[str, Any] = Field(
        description=(
            "The tool's return value. A string for log/describe output; "
            "a dict for structured data (e.g. search results, patch confirmations)."
        )
    )
    is_error: bool = Field(
        default=False,
        description="True if the tool execution failed. Claude will see this and adjust its plan.",
    )
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp of when the tool finished executing.",
    )

    model_config = ConfigDict(json_schema_extra={
            "example": {
                "tool_use_id": "toolu_01XzY",
                "name": "get_pod_logs",
                "output": "Error: OOMKilled — container exceeded memory limit of 256Mi",
                "is_error": False,
                "timestamp": "2024-01-15T10:30:01Z",
            }
        })


# ---------------------------------------------------------------------------
# Agent run model
# ---------------------------------------------------------------------------


class AgentRun(BaseModel):
    """
    Top-level record representing one Root Agent agent analysis session.

    Created when POST /agent/analyze is called and updated as the agent
    progresses through its diagnosis-and-remediation loop.
    """

    run_id: str = Field(description="Unique identifier for this run (UUID).")
    status: AgentStatus = Field(
        default=AgentStatus.PENDING,
        description="Current lifecycle state of the run.",
    )

    # --- Input ---
    alert_summary: str = Field(
        description=(
            "The triggering alert or symptom description provided by the caller. "
            "Example: 'Pod api-server-7d9f in production is CrashLoopBackOff'."
        )
    )
    namespace: str | None = Field(
        default=None,
        description="Kubernetes namespace hint extracted from or provided with the alert.",
    )
    cluster: str | None = Field(
        default=None,
        description="Cluster name this run targets. Used for Slack notifications.",
    )

    # --- Agent trace ---
    tool_calls: list[ToolCall] = Field(
        default_factory=list,
        description="Ordered list of every tool call the agent made during this run.",
    )
    tool_results: list[ToolResult] = Field(
        default_factory=list,
        description="Ordered list of results corresponding to each tool call.",
    )
    llm_steps: int = Field(
        default=0,
        description="Number of Claude API round-trips performed (for cost tracking).",
    )

    # --- Outcome ---
    diagnosis: str | None = Field(
        default=None,
        description="Human-readable root-cause diagnosis produced by the agent.",
    )
    fix_applied: str | None = Field(
        default=None,
        description="Description of the remediation action taken (if any).",
    )
    pending_fix: dict[str, Any] | None = Field(
        default=None,
        description=(
            "The proposed fix payload waiting for human approval. "
            "Present only when status == AWAITING_APPROVAL."
        ),
    )
    error_message: str | None = Field(
        default=None,
        description="Set when status == FAILED. Contains the exception or abort reason.",
    )

    # --- Timestamps ---
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp when the run was created.",
    )
    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp of the last status change.",
    )
    completed_at: datetime | None = Field(
        default=None,
        description="UTC timestamp when the run reached a terminal state.",
    )

    def add_tool_call(self, call: ToolCall) -> None:
        """Append a tool call to the run trace."""
        self.tool_calls.append(call)
        self.updated_at = datetime.now(timezone.utc)

    def add_tool_result(self, result: ToolResult) -> None:
        """Append a tool result to the run trace."""
        self.tool_results.append(result)
        self.updated_at = datetime.now(timezone.utc)

    def set_status(self, status: AgentStatus) -> None:
        """Transition to a new status and update the timestamp."""
        self.status = status
        self.updated_at = datetime.now(timezone.utc)
        if status in (AgentStatus.COMPLETED, AgentStatus.FAILED, AgentStatus.CANCELLED):
            self.completed_at = datetime.now(timezone.utc)

    model_config = ConfigDict(json_schema_extra={
            "example": {
                "run_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
                "status": "awaiting_approval",
                "alert_summary": "Pod api-server-7d9f in production is CrashLoopBackOff",
                "namespace": "production",
                "cluster": "prod-us-east-1",
                "tool_calls": [],
                "tool_results": [],
                "llm_steps": 3,
                "diagnosis": "Container is OOMKilled due to memory limit of 256Mi being too low.",
                "fix_applied": None,
                "pending_fix": {
                    "action": "patch",
                    "resource_type": "deployment",
                    "resource_name": "api-server",
                    "namespace": "production",
                    "patch_body": {
                        "spec": {
                            "template": {
                                "spec": {
                                    "containers": [
                                        {"name": "api-server", "resources": {"limits": {"memory": "512Mi"}}}
                                    ]
                                }
                            }
                        }
                    },
                },
                "error_message": None,
                "created_at": "2024-01-15T10:30:00Z",
                "updated_at": "2024-01-15T10:30:45Z",
                "completed_at": None,
            }
        })


# ---------------------------------------------------------------------------
# Request / response schemas for the API layer
# ---------------------------------------------------------------------------


class AnalyzeRequest(BaseModel):
    """Request body for POST /agent/analyze."""

    alert_summary: str = Field(
        description="Description of the Kubernetes alert or symptom to investigate.",
        min_length=10,
    )
    namespace: str | None = Field(
        default=None,
        description="Kubernetes namespace to scope the investigation (optional).",
    )
    cluster: str | None = Field(
        default=None,
        description="Cluster name for context and Slack notifications (optional).",
    )

    model_config = ConfigDict(json_schema_extra={
            "example": {
                "alert_summary": "Pod api-server-7d9f in production is CrashLoopBackOff",
                "namespace": "production",
                "cluster": "prod-us-east-1",
            }
        })


class ApproveRequest(BaseModel):
    """Request body for POST /agent/approve/{run_id}."""

    approved: bool = Field(
        description="True to approve and execute the pending fix; False to reject and abort."
    )
    approver: str | None = Field(
        default=None,
        description="Name or email of the operator approving the fix (for audit logging).",
    )

    model_config = ConfigDict(json_schema_extra={
            "example": {"approved": True, "approver": "alice@company.com"}
        })


class AgentRunSummary(BaseModel):
    """Lightweight projection of AgentRun for list responses."""

    run_id: str
    status: AgentStatus
    alert_summary: str
    namespace: str | None
    cluster: str | None
    llm_steps: int
    created_at: datetime
    completed_at: datetime | None
